# Generated by Django 4.2.2 on 2023-06-29 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('type', models.CharField(choices=[('L', 'Lifestyle'), ('S', 'Study'), ('A', 'Advice')], default=None, max_length=10, verbose_name='Type of post')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='Content')),
                ('image', models.ImageField(height_field='img_height', upload_to='images', width_field='img_width')),
                ('release_date', models.DateField()),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['release_date'],
            },
        ),
    ]
