# Generated by Django 4.2.2 on 2023-06-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, height_field='img_height', upload_to='images', width_field='img_width'),
        ),
    ]
