# Generated by Django 4.2.2 on 2023-06-30 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_height',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='post',
            name='url_width',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, height_field='url_height', upload_to='images', width_field='url_width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.DateField(default=datetime.date(2023, 6, 30)),
        ),
    ]
