# Generated by Django 4.2.2 on 2023-06-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0003_post_url_height_post_url_width_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.DateField(),
        ),
    ]
