# Generated by Django 4.2.2 on 2023-07-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0008_alter_post_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='statusType',
            field=models.CharField(choices=[('W', 'Writer'), ('F', 'Follower'), ('C', 'Critic')], default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userpic',
            field=models.ImageField(default='default.jpg', upload_to='media/images/userpic'),
        ),
    ]
