# Generated by Django 4.2.2 on 2023-07-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0011_alter_friendship_from_user_alter_friendship_to_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
