# Generated by Django 4.2.2 on 2023-07-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0012_rename_user_name_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='statusType',
            field=models.CharField(choices=[('Writer', 'Writer'), ('Follower', 'Follower'), ('Critic', 'Critic')], default='n/a', max_length=50),
        ),
    ]
