# Generated by Django 4.2.2 on 2023-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0013_alter_profile_statustype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.TextField(blank=True),
        ),
    ]
