# Generated by Django 4.2.2 on 2023-07-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0014_remove_profile_friends_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userpic',
            field=models.ImageField(default='media/images/userpic/default.jpg', upload_to='media/images/userpic'),
        ),
    ]
