# Generated by Django 4.2.2 on 2023-07-08 10:44

import dj_blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0017_alter_profile_userpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userpic',
            field=models.ImageField(default='images/userpic/default.jpg', upload_to=dj_blog_app.models.Profile.image_upload_to),
        ),
    ]
