# Generated by Django 4.2.2 on 2023-07-08 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0020_alter_profile_userpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='dj_blog_app.profile'),
        ),
    ]
