# Generated by Django 4.2.2 on 2023-07-08 23:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0021_friendship_timestamp_remove_profile_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='user'),
            preserve_default=False,
        ),
    ]
