# Generated by Django 4.2.2 on 2023-07-09 23:47

import dj_blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_blog_app', '0024_friendship_delete_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Study', 'Study'), ('Advice', 'Advice')], default=None, max_length=10, verbose_name='Type of post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userpic',
            field=models.ImageField(default='images/userpic/default.png', upload_to=dj_blog_app.models.Profile.image_upload_to),
        ),
    ]
